[package]
name = "png"
version = "0.17.2"
license = "MIT OR Apache-2.0"

description = "PNG decoding and encoding library in pure Rust"
categories = ["multimedia::images"]
authors = ["The image-rs Developers"]
repository = "https://github.com/image-rs/image-png.git"

edition = "2018"
include = [
    "/LICENSE-MIT",
    "/LICENSE-APACHE",
    "/README.md",
    "/CHANGES.md",
    "/src/",
    "/examples/",
    "/benches/",
]

[dependencies]
bitflags = "1.0"
crc32fast = "1.2.0"
deflate = "1.0.0"
tokio = {version = "1.15", features=["fs", "io-util"], optional=true}

[dependencies.miniz_oxide]
version = "0.5.1"

[dev-dependencies]
criterion = "0.3.1"
getopts = "0.2.14"
term = "0.6.1"
glob = "0.3"
rand = "0.7.0"
tokio = {version = "1.15", features=["fs", "io-util", "macros", "rt-multi-thread"]}

[dev-dependencies.glium]
version = "0.24"
features = ["glutin"]
default-features = false

[features]
default = ["async"]

unstable = []
benchmarks = []
async = ["tokio"]


[[bench]]
path = "benches/decoder.rs"
name = "decoder"
harness = false
